name: pawfeeder
description: "A new Flutter project."

# The following defines the version and environment for your app
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  mqtt_client: ^10.5.1
  mysql1: ^0.20.0
  provider: ^6.0.1
  intl: ^0.20.0
  image_picker: ^0.8.7+3
  universal_html: ^2.0.5
  image_picker_for_web: ^2.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/logo.png
